import React, { useState } from 'react';
import Footer from './Footer';
import Header from './Header';

export default function AiFaqsPage({ onNavigate }) {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState('All');
  const [openIndex, setOpenIndex] = useState(0);

  const categories = ['All', 'Connecting Sheets & Sites', 'Issue Diagnostics', 'Counter-Measures', 'Security & Privacy'];

  const faqs = [
    {
      category: 'Connecting Sheets & Sites',
      q: 'How do I connect my Google Sheets or Excel files to the AI Brain?',
      a: 'Connecting is as simple as signing in with your Google account or uploading your spreadsheet. You grant read/write permissions to specific sheets. Our connector maps your columns, headers, formulas, and data types automatically in under 60 seconds.'
    },
    {
      category: 'Connecting Sheets & Sites',
      q: 'What kind of websites or custom apps can I connect?',
      a: 'You can connect e-commerce websites (Shopify, WooCommerce, custom checkout flows), SaaS landing pages, internal admin portals, and web applications via our lightweight 1-line tracking script or direct webhook integrations.'
    },
    {
      category: 'Issue Diagnostics',
      q: 'How does the AI Brain detect issues and find root causes?',
      a: 'The AI Brain continuously cross-references numbers across your connected spreadsheets, site telemetry, and databases. When a discrepancy occurs (e.g. inventory formulas yielding negative stock, checkout drop-offs, delayed invoice payments), it traces the multi-step causal chain back to the exact root cause.'
    },
    {
      category: 'Counter-Measures',
      q: 'What exactly are Counter-Measures and how are they executed?',
      a: 'Counter-Measures are actionable, verified solutions generated by the AI Brain to fix the detected issue. For example: auto-correcting broken formulas in Google Sheets, re-routing traffic on an underperforming web page, notifying vendors of stock shortages, or sending task reminders to sales reps. You can review and approve them with 1-click or configure auto-execution rules.'
    },
    {
      category: 'Counter-Measures',
      q: 'Can the AI Brain update my Google Sheets directly?',
      a: 'Yes! If you enable write access, the AI Brain can fix broken formula syntax, insert calculated reorder quantities, and update reconciliation rows automatically with a complete audit log of all changes.'
    },
    {
      category: 'Security & Privacy',
      q: 'Is our proprietary business and spreadsheet data kept private?',
      a: '100% Yes. Your spreadsheet and website data is processed in dedicated encrypted memory and is never used to train public models. We enforce strict SOC2 Type II and zero-knowledge encryption standards.'
    }
  ];

  const filteredFaqs = faqs.filter(f => {
    const matchesCategory = activeCategory === 'All' || f.category === activeCategory;
    const matchesSearch = f.q.toLowerCase().includes(searchQuery.toLowerCase()) || f.a.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="min-h-screen bg-white text-gray-900 flex flex-col font-text selection:bg-[#008767] selection:text-white">
      {/* Unified Professional Header */}
      <Header currentPage="faqs" onNavigate={onNavigate} forceTheme="light" />

      {/* Hero Header */}
      <section className="w-full pt-16 pb-12 px-6 sm:px-10 lg:px-16 bg-white border-b border-gray-100">
        <div className="max-w-7xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-black text-white text-[11px] font-semibold tracking-wider uppercase mb-6 shadow-sm">
            <span className="w-2 h-2 bg-[#008767] inline-block rounded-[1px]" />
            <span>KNOWLEDGE BASE & FAQS</span>
          </div>

          <h1 className="font-headline font-normal text-4xl sm:text-5xl lg:text-6xl leading-[1.1] tracking-tight text-[#111827] max-w-4xl mb-6">
            Frequently Asked Questions about our AI Brain
          </h1>

          <p className="font-text text-base sm:text-lg text-gray-500 leading-relaxed max-w-3xl mb-8">
            Learn how easy it is to connect your Google Sheets, websites, and databases, how the AI diagnoses root causes, and how counter-measures work.
          </p>

          {/* Search & Category Pills */}
          <div className="space-y-6 pt-6 border-t border-gray-100">
            <div className="relative max-w-xl">
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search Google Sheets, website connectors, counter-measures..."
                className="w-full pl-10 pr-4 py-3 rounded-full bg-white border border-gray-200 text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:border-[#008767] focus:ring-2 focus:ring-[#008767]/20 transition-all shadow-sm"
              />
              <svg className="w-4 h-4 text-gray-400 absolute left-3.5 top-1/2 -translate-y-1/2" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <circle cx="11" cy="11" r="8" />
                <line x1="21" y1="21" x2="16.65" y2="16.65" />
              </svg>
            </div>

            <div className="flex items-center gap-2 overflow-x-auto no-scrollbar w-full pb-2">
              {categories.map((cat) => (
                <button
                  key={cat}
                  type="button"
                  onClick={() => setActiveCategory(cat)}
                  className={`px-4 py-2 rounded-full text-xs font-semibold whitespace-nowrap transition-all cursor-pointer ${
                    activeCategory === cat
                      ? 'bg-black text-white shadow-md scale-[1.02]'
                      : 'bg-white text-gray-600 hover:text-black hover:bg-gray-100 border border-gray-200'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Accordion FAQ Section */}
      <section className="w-full py-16 px-6 sm:px-10 lg:px-16 bg-gray-50/50 flex-1">
        <div className="max-w-4xl mx-auto space-y-4">
          {filteredFaqs.length === 0 ? (
            <div className="text-center py-16 bg-white rounded-2xl border border-gray-200">
              <p className="text-base font-semibold text-gray-700 mb-2">No matching questions found</p>
              <button
                type="button"
                onClick={() => {
                  setActiveCategory('All');
                  setSearchQuery('');
                }}
                className="text-xs font-bold text-[#008767] hover:underline"
              >
                Clear Filters
              </button>
            </div>
          ) : (
            filteredFaqs.map((faq, i) => {
              const isOpen = openIndex === i;
              return (
                <div
                  key={i}
                  className="bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm transition-all"
                >
                  <button
                    type="button"
                    onClick={() => setOpenIndex(isOpen ? -1 : i)}
                    className="w-full p-6 text-left flex items-center justify-between gap-4 cursor-pointer hover:bg-gray-50/50 transition-colors"
                  >
                    <div>
                      <span className="text-[10px] font-mono uppercase tracking-wider font-bold text-[#008767] block mb-1">
                        {faq.category}
                      </span>
                      <h3 className="font-headline font-bold text-base sm:text-lg text-gray-900 leading-snug">
                        {faq.q}
                      </h3>
                    </div>
                    <div className={`w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center shrink-0 transition-transform duration-200 ${isOpen ? 'rotate-180 bg-[#008767] text-white' : 'text-gray-500'}`}>
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                      </svg>
                    </div>
                  </button>

                  {isOpen && (
                    <div className="px-6 pb-6 pt-2 font-text text-sm text-gray-600 leading-relaxed border-t border-gray-100 animate-fade-in">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })
          )}
        </div>
      </section>

      {/* Reusable Universal Footer */}
      <Footer onNavigate={onNavigate} />
    </div>
  );
}
